<?php
/**
 * DISCLAIMER
 * Do not edit or add to this file if you wish to upgrade this module to newer
 * versions in the future.
 *
 * @category  Smile
 * @package   Smile\StoreLocator
 * @author    Romain Ruaud <romain.ruaud@smile.fr>
 * @copyright 2017 Smile
 * @license   Open Software License ("OSL") v. 3.0
 */
namespace Cleargo\AigleClearomniConnector\Block\View;

use Magento\Framework\Locale\ListsInterface;
use Magento\Framework\Locale\Resolver;
use Magento\Framework\Registry;
use Magento\Framework\View\Element\Template\Context;
use Smile\StoreLocator\Api\Data\RetailerTimeSlotInterface;
use Smile\StoreLocator\Helper\Schedule;
use Smile\StoreLocator\Model\Retailer\ScheduleManagement;

/**
 * Opening Hours display block
 *
 * @category Smile
 * @package  Smile\StoreLocator
 * @author   Romain Ruaud <romain.ruaud@smile.fr>
 */
class OpeningHours extends \Smile\StoreLocator\Block\View\OpeningHours
{
    protected $retailerId;
    protected $retailer;
    public function __construct(
        Context $context,
        Registry $coreRegistry,
        ScheduleManagement $scheduleManager,
        Schedule $scheduleHelper,
        ListsInterface $localeList,
        array $data = []
    ) {
        parent::__construct($context,$coreRegistry,$scheduleManager,$scheduleHelper,$localeList,$data);
    }
    public function getJsLayout()
    {
        $jsLayout = json_decode(parent::getJsLayout(),true);

        $jsLayout['components']['smile-storelocator-store']['retailerId'] = $this->retailerId;
        return json_encode($jsLayout);
    }

    /**
     * @return mixed
     */
    public function getRetailerId()
    {
        return $this->retailerId;
    }

    /**
     * @param mixed $retailId
     */
    public function setRetailerId($retailerId)
    {
        $this->retailerId = $retailerId;
    }

    public function getRetailer()
    {
        return  $this->retailer; // TODO: Change the autogenerated stub
    }
    public function setRetailer($retailer){
        $this->retailer=$retailer;
    }
    public function getWeekOpeningHours()
    {
        return parent::getWeekOpeningHours();
    }



}
